apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset-redis
  template:
    metadata:
      labels:
        app: superset-redis
    spec:
      containers:
      - name: superset-redis
        image: redis:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: superset-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: superset-redis

