apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: apache/superset:latest
        ports:
        - containerPort: 8088
        env:
        - name: SUPERSET_SECRET_KEY
          value: "your_super_secret_key"
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql+psycopg2://superset:superset@db:5432/superset"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        volumeMounts:
        - name: superset-home
          mountPath: /app/superset_home
      volumes:
      - name: superset-home
        persistentVolumeClaim:
          claimName: superset-home-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: superset
spec:
  type: LoadBalancer
  ports:
  - port: 8088
    targetPort: 8088
  selector:
    app: superset

